const players = [
    { vorname: 'LeBron', nachname: 'James', positions: ['PG', 'SG', 'SF', 'PF', 'C'], teams: [Team.CLE, Team.MIA, Team.LAL] },
    { vorname: 'Michael', nachname: 'Jordan', positions: ['SG', 'SF'], teams: [Team.CHI, Team.WAS] },
    { vorname: 'Kobe', nachname: 'Bryant', positions: ['SG', 'SF'], teams: [Team.LAL] },
    { vorname: 'Magic', nachname: 'Johnson', positions: ['PG', 'SG', 'PF'], teams: [Team.LAL] },
    { vorname: 'Larry', nachname: 'Bird', positions: ['SF', 'PF'], teams: [Team.BOS] },
    { vorname: 'Shaquille', nachname: 'O\'Neal', positions: ['C'], teams: [Team.LAL, Team.MIA, Team.PHO, Team.ORL] },
    { vorname: 'Tim', nachname: 'Duncan', positions: ['PF', 'C'], teams: [Team.SAS] },
    { vorname: 'Kevin', nachname: 'Garnett', positions: ['SF', 'PF', 'C'], teams: [Team.BOS, Team.MIN, Team.BKN] },
    { vorname: 'Dirk', nachname: 'Nowitzki', positions: ['PF', 'C'], teams: [Team.DAL] },
    { vorname: 'Hakeem', nachname: 'Olajuwon', positions: ['C'], teams: [Team.HOU, Team.TOR] },
    { vorname: 'Dwyane', nachname: 'Wade', positions: ['PG', 'SG'], teams: [Team.MIA, Team.CHI, Team.CLE] },
    { vorname: 'Kawhi', nachname: 'Leonard', positions: ['SF'], teams: [Team.SAS, Team.TOR, Team.LAC] },
    { vorname: 'Stephen', nachname: 'Curry', positions: ['PG'], teams: [Team.GSW] },
    { vorname: 'Kevin', nachname: 'Durant', positions: ['SG', 'SF', 'PF'], teams: [Team.SEA, Team.OKC, Team.GSW, Team.BKN, Team.PHO] },
    { vorname: 'Russell', nachname: 'Westbrook', positions: ['PG'], teams: [Team.OKC, Team.HOU, Team.WAS] },
    { vorname: 'James', nachname: 'Harden', positions: ['SG', 'PG'], teams: [Team.OKC, Team.HOU, Team.BKN, Team.PHI, Team.LAC] },
    { vorname: 'Chris', nachname: 'Paul', positions: ['PG'], teams: [Team.NOK, Team.NOH, Team.LAC, Team.HO, Team.OKC, Team.PHO, Team.GSW] },
    { vorname: 'Anthony', nachname: 'Davis', positions: ['PF', 'C'], teams: [Team.NOH, Team.NOP, Team.LAL] },
    { vorname: 'Paul', nachname: 'George', positions: ['SG', 'SF', 'PF'], teams: [Team.IND, Team.OKC, Team.LAC] },
    { vorname: 'Carmelo', nachname: 'Anthony', positions: ['SF', 'PF'], teams: [Team.DEN, Team.NYK, Team.OKC, Team.POR, Team.LAL] },
    { vorname: 'Kyrie', nachname: 'Irving', positions: ['PG', 'SG'], teams: [Team.CLE, Team.BOS, Team.BKN, Team.DAL] },
    { vorname: 'Damian', nachname: 'Lillard', positions: ['PG'], teams: [Team.POR, Team.MIL] },
    { vorname: 'Giannis', nachname: 'Antetokounmpo', positions: ['PG', 'SG', 'SF', 'PF'], teams: [Team.MIL] },
    { vorname: 'Karl-Anthony', nachname: 'Towns', positions: ['C', 'PF'], teams: [Team.MIN] },
    { vorname: 'Joel', nachname: 'Embiid', positions: ['C'], teams: [Team.PHI] },
    { vorname: 'Ben', nachname: 'Simmons', positions: ['PG'], teams: [Team.PHI, Team.BKN] },
    { vorname: 'Devin', nachname: 'Booker', positions: ['PG', 'SG'], teams: [Team.PHO] },
    { vorname: 'Jayson', nachname: 'Tatum', positions: ['SF', 'PF'], teams: [Team.BOS] },
    { vorname: 'Jimmy', nachname: 'Butler', positions: ['SG', 'SF', 'PF'], teams: [Team.CHI, Team.MIN, Team.PHI, Team.MIA] },
    { vorname: 'Donovan', nachname: 'Mitchell', positions: ['SG', 'PG'], teams: [Team.UTA, Team.CLE] },
    { vorname: 'Zion', nachname: 'Williamson', positions: ['PF'], teams: [Team.NOP] },
    { vorname: 'Luka', nachname: 'Dončić', positions: ['PG', 'SG'], teams: [Team.DAL] },
    { vorname: 'Trae', nachname: 'Young', positions: ['PG'], teams: [Team.ATL] },
    { vorname: 'Jamal', nachname: 'Murray', positions: ['PG', 'SG'], teams: [Team.DEN] },
    { vorname: 'Pascal', nachname: 'Siakam', positions: ['PF'], teams: [Team.TOR, Team.IND] },
    { vorname: 'De\'Aaron', nachname: 'Fox', positions: ['PG'], teams: [Team.SAC] },
    { vorname: 'Bradley', nachname: 'Beal', positions: ['SG'], teams: [Team.WAS, Team.PHO] },
    { vorname: 'Nikola', nachname: 'Jokić', positions: ['C'], teams: [Team.DEN] },
    { vorname: 'Kemba', nachname: 'Walker', positions: ['PG'], teams: [Team.CHA, Team.CHO, Team.BOS] },
    { vorname: 'Kristaps', nachname: 'Porziņģis', positions: ['PF', 'C'], teams: [Team.NYK, Team.DAL, Team.WAS, Team.BOS] },
    { vorname: 'Rudy', nachname: 'Gobert', positions: ['C'], teams: [Team.UTA, Team.MIN] },
    { vorname: 'DeMar', nachname: 'DeRozan', positions: ['SG', 'SF', 'PF'], teams: [Team.TOR, Team.SAS, Team.CHI] },
    { vorname: 'Kyle', nachname: 'Lowry', positions: ['PG'], teams: [Team.MEM, Team.HOU, Team.TOR, Team.MIA] },
    { vorname: 'Derrick', nachname: 'Rose', positions: ['PG'], teams: [Team.CHI, Team.NYK, Team.MIN, Team.DET, Team.NYK] },
    { vorname: 'Blake', nachname: 'Griffin', positions: ['PF', 'C'], teams: [Team.LAC, Team.DET, Team.BKN, Team.BOS] },
    { vorname: 'LaMarcus', nachname: 'Aldridge', positions: ['PF', 'C'], teams: [Team.POR, Team.SAS, Team.BKN] },
    { vorname: 'CJ', nachname: 'McCollum', positions: ['SG', 'PG'], teams: [Team.POR, Team.NOP] },
    { vorname: 'Brandon', nachname: 'Ingram', positions: ['SF', 'PF'], teams: [Team.LAL, Team.NOP] },
    { vorname: 'Andrew', nachname: 'Wiggins', positions: ['SF', 'PF'], teams: [Team.MIN, Team.GSW] },
    { vorname: 'Victor', nachname: 'Oladipo', positions: ['PG', 'SG'], teams: [Team.ORL, Team.OKC, Team.IND, Team.MIA] },
    { vorname: 'John', nachname: 'Wall', positions: ['PG'], teams: [Team.WAS] },
    { vorname: 'DeAndre', nachname: 'Ayton', positions: ['C'], teams: [Team.PHO, Team.POR] },
    { vorname: 'Ja', nachname: 'Morant', positions: ['PG'], teams: [Team.MEM] },
    { vorname: 'Chris', nachname: 'Bosh', positions: ['PF', 'C'], teams: [Team.TOR, Team.MIA] },
    { vorname: 'Dwight', nachname: 'Howard', positions: ['C', 'PF'], teams: [Team.ORL, Team.LAL, Team.HOU, Team.ATL, Team.CHO, Team.PHI] },
    { vorname: 'Kevin', nachname: 'Love', positions: ['PF', 'C'], teams: [Team.MIN, Team.CLE, Team.MIA] },
    { vorname: 'Paul', nachname: 'Millsap', positions: ['PF', 'C'], teams: [Team.UTA, Team.ATL, Team.DEN] },
    { vorname: 'Steve', nachname: 'Nash', positions: ['PG'], teams: [Team.PHO, Team.DAL, Team.LAL] },
    { vorname: 'Vince', nachname: 'Carter', positions: ['SG', 'SF', 'PF'], teams: [Team.TOR, Team.NJN, Team.ORL] },
    { vorname: 'Rajon', nachname: 'Rondo', positions: ['PG'], teams: [Team.BOS, Team.DAL, Team.SAC, Team.CHI, Team.NOP, Team.LAL] },
    { vorname: 'Al', nachname: 'Horford', positions: ['C'], teams: [Team.ATL, Team.BOS, Team.PHI] },
    { vorname: 'Marc', nachname: 'Gasol', positions: ['C'], teams: [Team.MEM, Team.TOR, Team.LAL] },
    { vorname: 'Dennis', nachname: 'Schröder', positions: ['PG', 'SG'], teams: [Team.ATL, Team.OKC, Team.LAL, Team.BOS, Team.TOR] },
    { vorname: 'Gordon', nachname: 'Hayward', positions: ['SF', 'PF'], teams: [Team.UTA, Team.BOS, Team.CHO] },
    { vorname: 'Jrue', nachname: 'Holiday', positions: ['PG', 'SG'], teams: [Team.PHI, Team.NOP, Team.MIL, Team.BOS] },
    { vorname: 'Zach', nachname: 'LaVine', positions: ['SG', 'PG', 'SF'], teams: [Team.MIN, Team.CHI] },
    { vorname: 'Nikola', nachname: 'Vučević', positions: ['C'], teams: [Team.PHI, Team.ORL, Team.CHI] },
    { vorname: 'Clint', nachname: 'Capela', positions: ['C'], teams: [Team.HOU, Team.ATL] },
    { vorname: 'Jaylen', nachname: 'Brown', positions: ['SG', 'SF'], teams: [Team.BOS] },
    { vorname: 'Julius', nachname: 'Randle', positions: ['PF', 'C'], teams: [Team.LAL, Team.NOP, Team.NYK] },
    { vorname: 'Bam', nachname: 'Adebayo', positions: ['C', 'PF'], teams: [Team.MIA] },
    { vorname: 'Fred', nachname: 'VanVleet', positions: ['PG', 'SG'], teams: [Team.TOR, Team.HOU] },
    { vorname: 'Danilo', nachname: 'Gallinari', positions: ['SF', 'PF', 'SG'], teams: [Team.NYK, Team.DEN, Team.LAC, Team.OKC, Team.ATL] },
    { vorname: 'Andre', nachname: 'Drummond', positions: ['C'], teams: [Team.DET, Team.PHI, Team.CHI] },
    { vorname: 'Tobias', nachname: 'Harris', positions: ['SF', 'PF'], teams: [Team.MIL, Team.ORL, Team.DET, Team.LAC, Team.PHI] },
    { vorname: 'Lou', nachname: 'Williams', positions: ['SG', 'PG'], teams: [Team.PHI, Team.ATL, Team.TOR, Team.LAL, Team.LAC, ] },
    { vorname: 'Eric', nachname: 'Bledsoe', positions: ['PG', 'SG'], teams: [Team.LAC, Team.PHO, Team.MIL, Team.NOP] },
    { vorname: 'Andre', nachname: 'Iguodala', positions: ['SF', 'SG', 'PF'], teams: [Team.PHI, Team.DEN, Team.GSW, Team.MIA] },
    { vorname: 'Derrick', nachname: 'Favors', positions: ['PF', 'C'], teams: [Team.NJN, Team.UTA, Team.NOP] },
    { vorname: 'Khris', nachname: 'Middleton', positions: ['SF', 'SG'], teams: [Team.MIL] },
    { vorname: 'Serge', nachname: 'Ibaka', positions: ['PF', 'C'], teams: [Team.OKC, Team.ORL, Team.TOR, Team.LAC] },
    { vorname: 'Malcolm', nachname: 'Brogdon', positions: ['PG', 'SG'], teams: [Team.MIL, Team.IND, Team.BOS] },
    { vorname: 'Myles', nachname: 'Turner', positions: ['C'], teams: [Team.IND] },
    { vorname: 'Robert', nachname: 'Covington', positions: ['SF', 'PF', 'C'], teams: [Team.PHI, Team.MIN, Team.POR, Team.LAC] },
    { vorname: 'Brook', nachname: 'Lopez', positions: ['C'], teams: [Team.NJN, Team.BKN, Team.LAL, Team.MIL] },
    { vorname: 'Jaren', nachname: 'Jackson Jr.', positions: ['C', 'PF'], teams: [Team.MEM] },
    { vorname: 'Dejounte', nachname: 'Murray', positions: ['PG', 'SG'], teams: [Team.SAS, Team.ATL] },
    { vorname: 'D\'Angelo', nachname: 'Russell', positions: ['PG'], teams: [Team.LAL, Team.BKN, Team.MIN] },
    { vorname: 'Shai', nachname: 'Gilgeous-Alexander', positions: ['PG', 'SG'], teams: [Team.LAC, Team.OKC] },
    { vorname: 'Jonathan', nachname: 'Isaac', positions: ['PF'], teams: [Team.ORL] },
    { vorname: 'Montrezl', nachname: 'Harrell', positions: ['PF', 'C'], teams: [Team.HOU, Team.LAC, Team.WAS, Team.PHI] },
    { vorname: 'Spencer', nachname: 'Dinwiddie', positions: ['PG', 'SG'], teams: [Team.BKN, Team.WAS, Team.DAL] },
    { vorname: 'Goran', nachname: 'Dragić', positions: ['PG', 'SG'], teams: ['PHO', 'MIA'] },
    { vorname: 'Kelly', nachname: 'Oubre Jr.', positions: ['SF'], teams: [Team.WAS, Team.PHO, Team.GSW, Team.CHO, Team.PHI] },
    { vorname: 'Derrick', nachname: 'White', positions: ['PG', 'SG'], teams: [Team.SAS, Team.BOS] },
    { vorname: 'Donte', nachname: 'DiVincenzo', positions: ['SG'], teams: [Team.MIL, Team.GSW, Team.NYK] },
    { vorname: 'Michael', nachname: 'Porter Jr.', positions: ['SF', 'PF'], teams: ['DEN'] },
    { vorname: 'John', nachname: 'Collins', positions: ['PF'], teams: [Team.ATL, Team.UTA] },
    { vorname: 'Christian', nachname: 'Wood', positions: ['PF', 'C'], teams: [Team.DET, Team.HOU, Team.DAL, Team.LAL] },
    { vorname: 'Jarrett', nachname: 'Allen', positions: ['C'], teams: [Team.BKN, Team.CLE] },
    { vorname: 'Domantas', nachname: 'Sabonis', positions: ['PF', 'C'], teams: [Team.OKC, Team.IND, Team.SAC] },
    { vorname: 'Terry', nachname: 'Rozier', positions: ['PG', 'SG'], teams: [Team.BOS, Team.CHO] },
    { vorname: 'Jusuf', nachname: 'Nurkić', positions: ['C'], teams: [Team.DEN, Team.POR] },
    { vorname: 'Gary', nachname: 'Harris', positions: ['SG'], teams: [Team.DEN, Team.ORL] },
    { vorname: 'Lonzo', nachname: 'Ball', positions: ['PG'], teams: [Team.LAL, Team.NOP] },
    { vorname: 'Collin', nachname: 'Sexton', positions: ['PG', 'SG'], teams: [Team.CLE, Team.UTA] },
    { vorname: 'Buddy', nachname: 'Hield', positions: ['SG', 'SF'], teams: [Team.NOP, Team.SAC, Team.IND] },
    { vorname: 'Aaron', nachname: 'Gordon', positions: ['SF', 'PF'], teams: [Team.ORL, Team.DEN] },
    { vorname: 'Robert', nachname: 'Williams III', positions: ['C'], teams: [Team.BOS] },
    { vorname: 'De\'Andre', nachname: 'Hunter', positions: ['SF'], teams: [Team.ATL] },
    { vorname: 'P.J.', nachname: 'Washington', positions: ['PF', 'C'], teams: [Team.CHO] },
    { vorname: 'Brandon', nachname: 'Clarke', positions: ['PF'], teams: [Team.MEM] },
    { vorname: 'Mikal', nachname: 'Bridges', positions: ['SF', 'SG'], teams: [Team.PHO, Team.BKN] },
    { vorname: 'Derrick', nachname: 'Jones Jr.', positions: ['SF', 'PF'], teams: [Team.MIA, Team.POR, Team.CHI, Team.DAL] },
    { vorname: 'Davis', nachname: 'Bertans', positions: ['PF'], teams: [Team.SAS, Team.WAS, Team.DAL] },
    { vorname: 'Bogdan', nachname: 'Bogdanović', positions: ['SG'], teams: [Team.SAC, Team.ATL] },
    { vorname: 'Goga', nachname: 'Bitadze', positions: ['C'], teams: [Team.IND, Team.ORL] },
    { vorname: 'Tyler', nachname: 'Herro', positions: ['SG'], teams: [Team.MIA] },
    { vorname: 'Jae\'Sean', nachname: 'Tate', positions: ['SF', 'PF'], teams: [Team.HOU] },
    { vorname: 'Rui', nachname: 'Hachimura', positions: ['PF'], teams: [Team.WAS, Team.LAL] },
    { vorname: 'Coby', nachname: 'White', positions: ['PG', 'SG'], teams: [Team.CHI] },
    { vorname: 'Cam', nachname: 'Reddish', positions: ['SF'], teams: [Team.ATL, Team.LAL] },
    { vorname: 'Anfernee', nachname: 'Simons', positions: ['SG'], teams: [Team.POR] },
    { vorname: 'Tyrese', nachname: 'Maxey', positions: ['PG', 'SG'], teams: [Team.PHI] },
    { vorname: 'Isaiah', nachname: 'Stewart', positions: ['C', 'PF'], teams: [Team.DET] },
    { vorname: 'Desmond', nachname: 'Bane', positions: ['SG'], teams: [Team.MEM] },
    { vorname: 'Tyrese', nachname: 'Haliburton', positions: ['PG', 'SG'], teams: [Team.SAC, Team.IND] },
    { vorname: 'Obi', nachname: 'Toppin', positions: ['PF'], teams: [Team.NYK, Team.IND] },
    { vorname: 'Allen', nachname: 'Iverson', positions: ['PG', 'SG'], teams: [Team.PHI, Team.DEN, Team.DET] },
    { vorname: 'Tracy', nachname: 'McGrady', positions: ['SG', 'SF'], teams: [Team.TOR, Team.ORL, Team.HOU, Team.DET, Team.ATL] },
    { vorname: 'Mark', nachname: 'Price', positions: ['PG'], teams: [Team.CLE, Team.GSW, Team.ORL] },
    { vorname: 'Tim', nachname: 'Hardaway', positions: ['PG'], teams: [Team.GSW, Team.MIA, Team.DAL] },
    { vorname: 'Lenny', nachname: 'Wilkens', positions: ['PG'], teams: [Team.STL, Team.CLE, Team.POR] },
    { vorname: 'Mitch', nachname: 'Richmond', positions: ['SG'], teams: [Team.GSW, Team.SAC, Team.WAS, Team.LAL] },
    { vorname: 'Detlef', nachname: 'Schrempf', positions: ['SF', 'PF'], teams: [Team.DAL, Team.IND, Team.SEA, Team.POR] },
    { vorname: 'Chris', nachname: 'Webber', positions: ['PF', 'C'], teams: [Team.GSW, Team.WSB, Team.WAS, Team.SAC, Team.PHI, Team.DET] },
    { vorname: 'Paul', nachname: 'Westphal', positions: ['SG', 'PG'], teams: [Team.BOS, Team.PHO, Team.NYK] },
    { vorname: 'Larry', nachname: 'Nance', positions: ['PF'], teams: [Team.PHO, Team.CLE] },
    { vorname: 'Dave', nachname: 'DeBusschere', positions: ['PF', 'SF'], teams: [Team.DET, Team.NYK] },
    { vorname: 'Bill', nachname: 'Walton', positions: ['C'], teams: [Team.POR, Team.SDC, Team.LAC] },
    { vorname: 'Bernard', nachname: 'King', positions: ['SF'], teams: [Team.NJN, Team.GSW, Team.NYK, Team.WSB] },
    { vorname: 'Chris', nachname: 'Mullin', positions: ['SF', 'SG'], teams: [Team.GSW, Team.IND] },
    { vorname: 'Bobby', nachname: 'Jones', positions: ['PF'], teams: [Team.DNA, Team.DEN, Team.PHI] },
    { vorname: 'Ben', nachname: 'Wallace', positions: ['PF', 'C'], teams: [Team.WAS, Team.ORL, Team.DET, Team.CHI] },
    { vorname: 'Maurice', nachname: 'Cheeks', positions: ['PG'], teams: [Team.PHI, Team.SAS, Team.NYK, Team.ATL] },   
    { vorname: 'Bill', nachname: 'Sharman', positions: ['SG'], teams: [Team.BOS] },    
    { vorname: 'Hal', nachname: 'Greer', positions: ['SG', 'PG'], teams: [Team.SYR, Team.PHI] }, 
    { vorname: 'Manu', nachname: 'Ginóbili', positions: ['SG'], teams: [Team.SAS] }, 
    { vorname: 'George', nachname: 'Mikan', positions: ['C'], teams: [Team.MNL] },
    { vorname: 'Dennis', nachname: 'Johnson', positions: ['PG', 'SG'], teams: [Team.SEA, Team.PHO, Team.BOS] },
    { vorname: 'Grant', nachname: 'Hill', positions: ['SG', 'SF'], teams: [Team.DET, Team.ORL, Team.PHO] },
    { vorname: 'Shawn', nachname: 'Marion', positions: ['PF', 'SF'], teams: [Team.PHO, Team.DAL, Team.CLE] },
    { vorname: 'Tiny', nachname: 'Archibald', positions: ['PG'], teams: [Team.CIN, Team.KCO, Team.BOS, Team.MIL] },
    { vorname: 'Chauncey', nachname: 'Billups', positions: ['PG', 'SG'], teams: [Team.BOS, Team.DEN, Team.MIN, Team.DET] },
    { vorname: 'Kevin', nachname: 'Johnson', positions: ['PG'], teams: [Team.CLE, Team.PHO, ] },
    { vorname: 'Dikembe', nachname: 'Mutombo', positions: ['C'], teams: [Team.DEN, Team.ATL, Team.PHI, Team.NYK, Team.HOU] },
    { vorname: 'Pau', nachname: 'Gasol', positions: ['C', 'PF'], teams: [Team.MEM, Team.LAL, Team.CHI, Team.SAS] },
    { vorname: 'Tom', nachname: 'Heinsohn', positions: ['PF', 'SF'], teams: [Team.BOS] },
    { vorname: 'Tony', nachname: 'Parker', positions: ['PG'], teams: [Team.SAS, Team.CHO] },
    { vorname: 'Dave', nachname: 'Cowens', positions: ['PF', 'C'], teams: [Team.BOS] },
    { vorname: 'Robert', nachname: 'Parish', positions: ['C'], teams: [Team.GSW, Team.BOS, Team.CHH, Team.CHI] },
    { vorname: 'Bob', nachname: 'Lanier', positions: ['C'], teams: [Team.DET, Team.MIL] },
    { vorname: 'Sidney', nachname: 'Moncrief', positions: ['SG', 'PG'], teams: [Team.MIL, Team.ATL] },
    { vorname: 'Jerry', nachname: 'Lucas', positions: ['C', 'PF'], teams: [Team.CIN, Team.SFW, Team.NYK] },
    { vorname: 'Dennis', nachname: 'Rodman', positions: ['PF', 'C'], teams: [Team.DET, Team.SAS, Team.CHI] },
    { vorname: 'Artis', nachname: 'Gilmore', positions: ['C'], teams: [Team.KEN, Team.CHI, Team.SAS, Team.BOS] },
    { vorname: 'James', nachname: 'Worthy', positions: ['PF', 'SF'], teams: [Team.LAL] },
    { vorname: 'Rick', nachname: 'Barry', positions: ['SF'], teams: [Team.SFW, Team.WSA, Team.NYA, Team.GSW, Team.HOU] },
    { vorname: 'Jason', nachname: 'Kidd', positions: ['PG', 'SG'], teams: [Team.DAL, Team.PHO, Team.NJN, Team.NYK] },
    { vorname: 'Adrian', nachname: 'Dantley', positions: ['SF'], teams: [Team.BUF, Team.LAL, Team.UTA, Team.DET, Team.DAL] },
    { vorname: 'Wes', nachname: 'Unseld', positions: ['C'], teams: [Team.BAL, Team.CAP, Team.WSB] },
    { vorname: 'Reggie', nachname: 'Miller', positions: ['SG'], teams: [Team.IND] },
    { vorname: 'Ray', nachname: 'Allen', positions: ['SG'], teams: [Team.MIL, Team.SEA, Team.BOS, Team.MIA] },
    { vorname: 'Dominique', nachname: 'Wilkins', positions: ['SF'], teams: [Team.ATL, Team.BOS, Team.SAS] },
    { vorname: 'Elvin', nachname: 'Hayes', positions: ['PF', 'C'], teams: [Team.SDR, Team.HOU, Team.BAL, Team.CAP, Team.WSB] },
    { vorname: 'Sam', nachname: 'Jones', positions: ['SG'], teams: [Team.BOS] },
    { vorname: 'George', nachname: 'Gervin', positions: ['SG', 'SF'], teams: [Team.VIR, Team.SAA, Team.SAS, Team.CHI] },
    { vorname: 'Kevin', nachname: 'McHale', positions: ['PF'], teams: [Team.BOS] },
    { vorname: 'Paul', nachname: 'Pierce', positions: ['SF', 'SG'], teams: [Team.BOS, Team.BKN, Team.WAS, Team.LAC] },
    { vorname: 'Patrick', nachname: 'Ewing', positions: ['C', 'PF'], teams: [Team.NYK, Team.SEA, Team.ORL] },
    { vorname: 'Dolph', nachname: 'Schayes', positions: ['PF', 'C'], teams: [Team.SYR] },
    { vorname: 'Gary', nachname: 'Payton', positions: ['PG'], teams: [Team.SEA, Team.LAL, Team.BOS, Team.MIA] },
    { vorname: 'Isiah', nachname: 'Thomas', positions: ['PG'], teams: [Team.DET] },
    { vorname: 'Bob', nachname: 'Cousy', positions: ['PG'], teams: [Team.BOS] },
    { vorname: 'Walt', nachname: 'Frazier', positions: ['PG'], teams: [Team.NYK, Team.CLE] },
    { vorname: 'Clyde', nachname: 'Drexler', positions: ['SG'], teams: [Team.POR, Team.HOU] },
    { vorname: 'Scottie', nachname: 'Pippen', positions: ['SF'], teams: [Team.CHI, Team.HOU, Team.POR] },
    { vorname: 'Julius', nachname: 'Erving', positions: ['SF', 'SG'], teams: [Team.VIR, Team.NYA, Team.PHI] },
    { vorname: 'John', nachname: 'Stockton', positions: ['PG'], teams: [Team.UTA] },
    { vorname: 'Elgin', nachname: 'Baylor', positions: ['SF'], teams: [Team.MNL, Team.LAL] },
    { vorname: 'Bob', nachname: 'Pettit', positions: ['PF', 'C'], teams: [Team.MLH, Team.STL] },
    { vorname: 'John', nachname: 'Havlicek', positions: ['SF', 'SG'], teams: [Team.BOS] },
    { vorname: 'Charles', nachname: 'Barkley', positions: ['PF', 'SF'], teams: [Team.PHI, Team.PHO, Team.HOU] },
    { vorname: 'Moses', nachname: 'Malone', positions: ['PF', 'C'], teams: [Team.UTS, Team.SSL, Team.HOU, Team.PHI, Team.WSB, Team.ATL, Team.MIL] },
    { vorname: 'Karl', nachname: 'Malone', positions: ['PF'], teams: [Team.UTA, Team.LAL] },
    { vorname: 'David', nachname: 'Robinson', positions: ['C'], teams: [Team.SAS] },
    { vorname: 'Oscar', nachname: 'Robertson', positions: ['PG'], teams: [Team.CIN, Team.MIL] },
    { vorname: 'Jerry', nachname: 'West', positions: ['PG', 'SG'], teams: [Team.LAL] },
    { vorname: 'Wilt', nachname: 'Chamberlain', positions: ['C'], teams: [Team.PHW, Team.SFW, Team.PHI, Team.LAL] },
    { vorname: 'Bill', nachname: 'Russel', positions: ['C'], teams: [Team.BOS] },
    { vorname: 'Kareem', nachname: 'Abdul-Jabbar', positions: ['C'], teams: [Team.MIL, Team.LAL] },
    { vorname: 'Jamal', nachname: 'Crawford', positions: ['SG', 'PG'], teams: [Team.CHI, Team.NYK, Team.GSW, Team.ATL, Team.POR, Team.LAC, Team.MIN, Team.PHO] },
    { vorname: 'Joe', nachname: 'Johnson', positions: ['SG', 'SF'], teams: [Team.BOS, Team.PHO, Team.ATL, Team.BKN, Team.UTA] },
    { vorname: 'Michael', nachname: 'Finley', positions: ['SF', 'SG'], teams: [Team.PHO, Team.DAL, Team.SAS] },
    { vorname: 'Sam', nachname: 'Cassell', positions: ['PG'], teams: [Team.HOU, Team.NJN, Team.MIL, Team.MIN, Team.LAC] },
    { vorname: 'Jeff', nachname: 'Hornacek', positions: ['SG', 'PG'], teams: [Team.PHO, Team.PHI, Team.UTA] },
    { vorname: 'Mookie', nachname: 'Blaylock', positions: ['PG'], teams: [Team.NJN, Team.ATL, Team.GSW] },
    { vorname: 'Lou', nachname: 'Hudson', positions: ['SG', 'SF'], teams: [Team.STL, Team.ATL, Team.LAL] },
    { vorname: 'Kevin', nachname: 'Willis', positions: ['PF', 'C'], teams: [Team.ATL, Team.MIA, Team.HOU, Team.TOR, Team.DEN, Team.SAS] },
    { vorname: 'Tree', nachname: 'Rollins', positions: ['C'], teams: [Team.ATL, Team.CLE, Team.HOU, Team.ORL] },
    { vorname: 'Buck', nachname: 'Williams', positions: ['PF'], teams: [Team.NJN, Team.POR, Team.NYK] },
    { vorname: 'Richard', nachname: 'Jefferson', positions: ['SF'], teams: [Team.NJN, Team.MIL, Team.SAS, Team.GSW, Team.UTA, Team.DAL, Team.CLE] },
    { vorname: 'Derrick', nachname: 'Coleman', positions: ['PF', 'C'], teams: [Team.NJN, Team.PHI, Team.CHH] },
    { vorname: 'Dražen', nachname: 'Petrović', positions: ['SG'], teams: [Team.POR, Team.NJN] },
    { vorname: 'Kenyon', nachname: 'Martin', positions: ['PF', 'C'], teams: [Team.NJN, Team.DEN] },
    { vorname: 'Kerry', nachname: 'Kittles', positions: ['SG'], teams: [Team.NJN] },
    { vorname: 'Muggsy', nachname: 'Bogues', positions: ['PG'], teams: [Team.WSB, Team.CHH, Team.GSW, Team.TOR] },
    { vorname: 'Dell', nachname: 'Curry', positions: ['SG'], teams: [Team.UTA, Team.CLE, Team.CHH, Team.MIL, Team.TOR] },
    { vorname: 'Glen', nachname: 'Rice', positions: ['SF'], teams: [Team.MIA, Team.CHH, Team.LAL, Team.NYK, Team.HOU] },
    { vorname: 'Gerald', nachname: 'Wallace', positions: ['SF', 'PF'], teams: [Team.SAC, Team.CHA, Team.POR, Team.BOS] },
    { vorname: 'Anthony', nachname: 'Mason', positions: ['PF', 'SF', 'C'], teams: [Team.NYK, Team.CHH, Team.MIA, Team.MIL] },
    { vorname: 'Larry', nachname: 'Johnson', positions: ['PF', 'SF'], teams: [Team.CHH, Team.NYK] },
    { vorname: 'Alonzo', nachname: 'Mourning', positions: ['C', 'PF'], teams: [Team.CHH, Team.MIA] },
    { vorname: 'Emeka', nachname: 'Okafor', positions: ['C', 'PF'], teams: [Team.CHA, Team.NOH, Team.WAS] },
    { vorname: 'Bob', nachname: 'Love', positions: ['PF', 'SF'], teams: [Team.CIN, Team.CHI] },
    { vorname: 'Horace', nachname: 'Grant', positions: ['C', 'PF'], teams: [Team.CHI, Team.ORL, Team.SEA, Team.LAL, Team.ORL] },
    { vorname: 'Chet', nachname: 'Walker', positions: ['SF'], teams: [Team.SYR, Team.PHI, Team.CHI] },
    { vorname: 'Jerry', nachname: 'Sloan', positions: ['SG', 'SF'], teams: [Team.BAL, Team.CHI] },
    { vorname: 'Luol', nachname: 'Deng', positions: ['SF', 'PF'], teams: [Team.CHI, Team.MIA, Team.LAL] },
    { vorname: 'Brad', nachname: 'Daugherty', positions: ['C'], teams: [Team.CLE] },
    { vorname: 'Zydrunas', nachname: 'Ilgauskas', positions: ['C'], teams: [Team.CLE, Team.MIA] },
    { vorname: 'Austin', nachname: 'Car', positions: ['SG'], teams: [Team.CLE] },
    { vorname: 'Hot Rod', nachname: 'Williams', positions: ['C', 'PF'], teams: [Team.CLE, Team.PHO] },
    { vorname: 'Ron', nachname: 'Harper', positions: ['SG', 'PG'], teams: [Team.CLE, Team.LAC, Team.CHI, Team.LAL] },
    { vorname: 'Rolando', nachname: 'Blackman', positions: ['SG'], teams: [Team.DAL, Team.NYK] },
    { vorname: 'Mark', nachname: 'Aguirre', positions: ['SF'], teams: [Team.DAL, Team.DET] },
    { vorname: 'Tyson', nachname: 'Chandler', positions: ['C', 'PF'], teams: [Team.CHI, Team.NOK, Team.NOH, Team.CHA, Team.DAL, Team.PHO, Team.LAL] },
    { vorname: 'Brad', nachname: 'Davis', positions: ['PG'], teams: [Team.DAL] },
    { vorname: 'Jason', nachname: 'Terry', positions: ['SG', 'PG'], teams: [Team.ATL, Team.DAL, Team.BOS, Team.HOU, Team.MIL] },
    { vorname: 'Derek', nachname: 'Harper', positions: ['PG', 'SG'], teams: [Team.DAL, Team.NYK, Team.ORL, Team.LAL] },
    { vorname: 'Alex', nachname: 'English', positions: ['SF'], teams: [Team.MIL, Team.IND, Team.DEN, Team.DAL] },
    { vorname: 'David', nachname: 'Thompson', positions: ['SG', 'SF'], teams: [Team.DNA, Team.DEN, Team.SAS] },
    { vorname: 'Dan', nachname: 'Issel', positions: ['C', 'PF'], teams: [Team.KEN, Team.DNA, Team.DEN] },
    { vorname: 'Fat', nachname: 'Lever', positions: ['PG', 'SG'], teams: [Team.POR, Team.DEN, Team.DAL] },
    { vorname: 'Kiki', nachname: 'Vandeweghe', positions: ['SF', 'PF'], teams: [Team.DEN, Team.POR, Team.NYK, Team.LAC] },
    { vorname: 'Joe', nachname: 'Dumars', positions: ['SG', 'PG'], teams: [Team.DET] },
    { vorname: 'Bill', nachname: 'Laimbeer', positions: ['C'], teams: [Team.CLE, Team.DET] },
    { vorname: 'Richard', nachname: 'Hamilton', positions: ['SG', 'SF'], teams: [Team.WAS, Team.DET, Team.CHI] },
    { vorname: 'Klay', nachname: 'Thompson', positions: ['SG', 'SF'], teams: [Team.GSW] },
    { vorname: 'Draymond', nachname: 'Green', positions: ['PF', 'SF'], teams: [Team.GSW] },
    { vorname: 'Nate', nachname: 'Thurmond', positions: ['C', 'PF'], teams: [Team.SFW, Team.GSW, Team.CHI, Team.CLE] },
    { vorname: 'Paul', nachname: 'Arizin', positions: ['SF'], teams: [Team.PHW] }
];


function getPlayers() {
  return players;
}